name: Build tar.gz file

on:
  push:
    branches:
      - branchAutoMake
  pull_request:
    branches:
      - branchAutoMake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: AutoMake work
      run: |
        ./configure
        make dist
