name: Docker Build and Push

on:
  push:
    branches:
      - main
      - branchHTTPserver
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push multi-arch Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/http-server-project:latest

      # Create and push manifest
      - name: Create and Push Manifest
        run: |
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/http-server-project:latest \
            --amend ${{ secrets.DOCKER_USERNAME }}/http-server-project:amd64 \
            --amend ${{ secrets.DOCKER_USERNAME }}/http-server-project:arm64
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/http-server-project:latest
